repos:
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        language: system
        entry: pytest -v
        always_run: true
        pass_filenames: false
        stages: [commit]
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        language_version: python3.10
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        exclude: "alembic"
